modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Extended%20Creative%20Inventory"
logoFile="icon.png"

[[mods]]
modId="extendedcreativeinventory"
version="2.1"
displayName="Extended Creative Inventory"
displayURL="https://curseforge.com/minecraft/mc-mods/extended-creative-inventory"
authors="Rick South"
description='''Adds all items which by default aren't in the creative inventory to a custom Extended tab.
If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Robert Gilbert, Shana Gitnick, Sija, Tyler Behl, Wendi S   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.extendedcreativeinventory]]
    modId="collective"
    mandatory=true
    versionRange="[6.45,)"
    ordering="NONE"
    side="BOTH"